### ISSUE TITLE
Sigterm conky when work with docker

### ISSUE THREAD

**Issue by Crandel** [brndnmtthws/conky#471]
conky 1.10.8_pre compiled Mon Mar 12 19:26:00 UTC 2018 for Linux 4.15.8-1-ARCH x86_64

When I restart docker conteiners, I got error

```
conky: too many interfaces used (limit is 64) 
terminate called after throwing an instance of 'std::system_error'
  what():  Resource deadlock avoided
```

Maybe its connected with docker network

My [config](https://github.com/Crandel/home/blob/master/.conky.lua)

**Comment by Barben360** [comment]
Indeed there is an issue when using Docker.
In Conky's code, a static array of 64 elements is created to store the internet interfaces of your machine. When you use docker, virtual ethernet networks are created with random names. When Conky reads a new interface, it adds it to the array, but there is no process to remove them. Therefore, when the 65th interface is discovered, it tries to add it outside of the array and crashes.
I am currently working on a solution for that but everything I tried is not working very well. I'll tell you if I can come with a solution.

**Comment by Barben360** [comment]
Fixed in [my fork](https://github.com/Barben360/conky). I opened a pull request.

**Comment by sumdog** [comment]
I was experiencing this issue too and realized it must be related to Docker's virtual interfaces. Glad to see it's already reported.

**Comment by brndnmtthws** [comment]
Fixed with #479.

**Comment by thomasplevy** [comment]
@brndnmtthws I'm still seeing this issue on Ubuntu after installation via apt. It looks like the latest version available as a .deb is 1.10.8 and this fix was included in 1.11

I don't have any idea how releasing to various package managers works but is there anyway (other than compiling from the source) for Ubuntu / Debian users to get the latest version?
